# fly.toml app configuration file generated for insights-frontend on 2023-08-14T09:38:01-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "insights-frontend"
primary_region = "ewr"
swap_size_mb = 512

[build]
  dockerfile = "frontend/Dockerfile"

[env]
  PYTHONPATH = "client/"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
