# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "insight-ai-api"
primary_region = "ewr"
swap_size_mb = 512

[build]
dockerfile = "Dockerfile"

[[services]]
internal_port = 8000
processes = ["app"]

[[services.ports]]
handlers = ["http"]
port = 8000
force_https = true

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
