[project]
name = "insight-ai-api"
version = ["version"]
readme = "README.md"

[tool.bandit]
exclude_dirs = [".idea"]
skips = ["B104"]

# black configuration
[tool.black]
line-length = 88

# flake8 configuration
[tool.flake8]
exclude = '(\.idea/|app/fly.toml)'

[tool.pylint]
skips = ["E0401"]
