[project]
name = "insight-ai-api"
version = ["version"]
readme = "README.md"

[tool.bandit]
exclude = "B104"

# black configuration
[tool.black]
line-length = 88
exclude = '(\.idea/|app/fly.toml)'

# flake8 configuration
[tool.flake8]
exclude = '.idea,app/fly.toml'
