# fly.toml app configuration file generated for insight-ai-api on 2023-08-03T19:42:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "insight-ai-api"
primary_region = "ewr"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]

[[services]]
  protocol = "tcp"
  internal_port = 8000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 8443
    handlers = ["tls", "http"]
