# fly.toml app configuration file generated for insight-ai-api on 2023-08-14T09:29:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "insight-ai-api"
primary_region = "ewr"

[build]
  dockerfile = "../Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
